# .streamlit/secrets.toml

[passwords]
# Follow the rule: username = "password"
ian = "Password22!"
troy = "Password22!"
jeremy = "Password22!"
william = "Password22!"
bahaa = "Password22!"
stephen = "Password22!"